title:            DTC
tagline:          A beautiful theme.
description:      Describe your website.
canonical: http://jekyll.gtat.me

# Owner/author information
owner:
  name:           Te-Lung David Chen
  avatar:         todo
  bio:            todo
  email:          d.tchen@ucla.edu
  twitter:        todo
  github:         deeTEEcee
  instagram:      todo
  location:       "Shinjuku, Tokyo"

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
  - title: Blog
    url: /blog
  - title: Journey To Japan
    url: /food
  - title: Projects
    url: /projects
  - title: Github
    url: https://github.com/deeteecee
    external: true

# personal projects
projects:
  - name: "react-calendar"
    description: "google-calendar-like react component"
    url: "https://github.com/deeTEEcee/react-calendar"
  - name: "relocation lifestyle"
    description: "crowd-sourcing resources for relocation or foreign country resources"
    url: ""

# either side projects or job-related
personal_history:
  - name: "rakuten-scraper"
    description: "how to web scrape a huge site like rakuten"
    url: "https://github.com/deeteecee/rakuten-scraper"
  - name: "stack-overflow-clone"
    description: "created while learning how mongodb works along with web sockets"
    url: "http://stack-overflow-clone.herokuapp.com/"
  - name: "urbandictionary-like site"
    description: "a desire to make a non-slang version of urbandictionary (making the transition from django -> rails)"
    url: "http://downtoenglish.herokuapp.com/"
  - name: "dodge game"
    description: "learning iOS, Cocos2D, and getting a touch of what game dev is like"
    url: "https://www.youtube.com/embed/oOO74rflqMI"



# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Tokyo/Japan
future:      true
highlighter: pygments
markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
