title:            DTC
tagline:          A beautiful theme.
description:      Describe your website.
canonical: http://jekyll.gtat.me

# Owner/author information
owner:
  name:           Te-Lung David Chen
  avatar:         todo
  bio:            todo
  email:          d.tchen@ucla.edu
  twitter:        todo
  github:         deeTEEcee
  instagram:      todo
  location:       "Shinjuku, Tokyo"

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
  - title: Blog
    url: /blog
  - title: Projects
    url: /projects
  - title: Github
    url: https://github.com/deeteecee
    external: true

# personal projects
projects:
  - name: "Down to English"
    description: "Learning rails for the first time: one week wireframing and rails and one week developing. The question to myself was how hard is it to learn a new framework and 'deploy' somewhere after only doing web development for a year."
    url: "http://downtoenglish.herokuapp.com/"
    image:
  - name: "Dodge Random Flying Balls Game"
    description: "Learning iOS, Cocos2D, and getting a touch of what game dev is like"
    url: "https://www.youtube.com/embed/oOO74rflqMI"

# either side projects or job-related
contributions:
  - name: "Independa"
    url: "http://independa.com/"
    image:
  - name: "Conyac"
    url: "http://conyac.cc/"
    image: 



# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Tokyo/Japan
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
